services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: abcd1590
    container_name: application-dinosaur-api

  db:
    image: postgres
    volumes:
      - ./Postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1590
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    container_name: db_postgres










