CREATE TABLE student (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    register_date DATE NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    name VARCHAR(60) NOT NULL,
    age INT NOT NULL
);